# Generated by Django 2.0.4 on 2018-04-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='goal_description',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='goal_id',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='goal_type',
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='name',
            field=models.CharField(default='scrumystatus', max_length=255),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='status_id',
            field=models.ForeignKey(default='not set', on_delete=django.db.models.deletion.CASCADE, to='scrumyapp.GoalStatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('V', 'Verified'), ('D', 'Done'), ('WT', 'Weekly Task'), ('DT', 'Daily Task')], max_length=1),
        ),
    ]
