# Generated by Django 2.0.4 on 2018-04-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumyapp', '0002_auto_20180424_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalstatus',
            name='verified_by',
        ),
        migrations.AlterField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('V', 'Verified'), ('D', 'Done'), ('WT', 'Weekly Task'), ('DT', 'Daily Task')], max_length=2),
        ),
    ]
